### ISSUE TITLE
When slicing, an incorrect sized skirt/outline is created

### ISSUE THREAD

**Issue by zubairhamed** [MosaicManufacturing/canvas-issues#110]
**Describe the bug**
When slicing, an incorrect sized skirt/outline is created

**To Reproduce**
1. Import a model
2. Scale model
3. Slice

**Expected behavior**
The skirt/outline drawn should be around the model of the appropriate scaled size. What i'm seeing is a skirt/outline of the original imported size of the model.

**Screenshots**
<img width="1673" alt="Screenshot 2019-07-10 at 20 23 44" src="https://user-images.githubusercontent.com/2336402/60994490-ee2abc00-a350-11e9-92c6-bcd85161ec88.png">

**Operating System (please complete the following information):**

**Additional context**

**Comment by zubairhamed** [comment]
also it seems that the top object (the Hono logo) bleeds into the bottom white base somehow.

**Comment by brandonbloch** [comment]
Hi Zubair,

I'm pretty confident this issue is not related to the scale of the model, as scale and other transformations are applied before the files even get to the slicing engine. Rather, I believe your model is not flat on the bottom. The skirt outlines the paths of the first layer, rather than the overall shape of the model. Can you take a look at the first layer using the sliders on the right, and see what the first layer looks like?
