### ISSUE TITLE
Purge block is partially overlapped on the model

### ISSUE THREAD

**Issue by golden-snake** [MosaicManufacturing/canvas-issues#112]
**Describe the bug**
Canvas doesn't automatically detect a purge block is too close a model before slicing (see attachment).

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1920" alt="Screenshot 2019-07-27 07 50 02" src="https://user-images.githubusercontent.com/52556984/61996189-6f1ece80-b046-11e9-962d-3b54fc89a581.png">

**Operating System (please complete the following information):**

**Additional context**

**Comment by uilleann** [comment]
I have this as well.  Prior to the splice it looks like adequate space between the block an the print and then after splice it looks like this.  So I move the part well away from the block before splicing.  But this is definitely an issue that needs to be fixed.

**Comment by golden-snake** [comment]
Chroma doesn't have that problem.

**Comment by brandonbloch** [comment]
Hi there,

Yes, this is definitely an issue. The tower preview that is displayed before slicing should always constitute a worst-case size (so that what is created is always smaller than, or the same size as, the preview). However, the bug is really the slicing engine producing more transitions within a layer than is expected, hence the tower being larger than expected.

**Comment by brandonbloch** [comment]
Hi all, these pesky issues should now be resolved! Happy printing!
