### ISSUE TITLE
Add print size (x, y, z coordinates)

### ISSUE THREAD

**Issue by binux14** [MosaicManufacturing/canvas-issues#13]
**Is your feature request related to a problem? Please describe.**
Not a problem but I am not sure how big my print will actually be.

**Describe the solution you'd like**
It would be nice to have a the size of the print on each of the 3 axis (x, y, z). 

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
N/A

**Comment by biscuitlad** [comment]
This is totally a problem for me. I'm slicing table top miniatures (hence height of figures is critical) and some of the print times are between 3-8 hours. I've no idea how big the prints are. How can you use a slicer that doesn't give that information? What happens if someone has used inches instead of mm in their STL export? Absolutely essential and unusable until you add it. I wouldn't risk a 5 hour print to discover it was the wrong height at the end of the print...?? I mean I just don't get the point of a scale feature when you have no idea what your scaling? What's the point? You have to print it first and try and work it out manually?

**Comment by brandonbloch** [comment]
Hi @binux14 and @biscuitlad,

Thank you for your feedback! We will be adding this functionality in our next update. You will be able to see the combined bounding box of whatever is selected in the Place step, as well as the overall bounding box of the print in the Preview step.

In the meantime @biscuitlad, I would recommend using http://gcode.ws to find out the bounding box of the print (under the "Model info" tab once you load a file). I hope this works for you until we build the functionality directly into CANVAS.

Cheers,
Brandon

**Comment by brandonbloch** [comment]
Hi @binux14 and @biscuitlad,

We have just put out an update to CANVAS that allows you to scale a model to certain dimensions (in mm) in addition to the scale factor. The dimensions will update based on what models are selected, so by selecting all models you can see the overall build dimensions of the print.

<img width="246" alt="screen shot 2018-09-11 at 5 46 52 pm" src="https://user-images.githubusercontent.com/217964/45389714-c1036500-b5ea-11e8-9dcc-07b6b43baf57.png">

We'll keep this issue open until we have build dimensions included in the print summary. In the meantime, hopefully this is sufficient for your use cases!

Cheers,
Brandon

**Comment by biscuitlad** [comment]
Cool, many thanks. I'll get testing!
