### ISSUE TITLE
Incorrect slicing of multicolor model

### ISSUE THREAD

**Issue by mygoodname631** [MosaicManufacturing/canvas-issues#136]
The model generated by the slicer does not match the original image.

To reproduce, retrieve and slice the Mets logo from the share link:  [https://share.canvas3d.io/projects/588908b61ade479e2f0c750c0fb84db5](url)
 
The sliced preview should match the original logo, but it doesn't.  Most obvious on the baseball stitching on the left and the white notch that appears on the left of the "M".  First image is the model before slicing, 2nd is the result.  Also a little hard to tell but the sliced model does not fully fill the area with filmament.  Originally thought it was my printer but the result actually matched the odd image in the preview down to the thin fill-in.

![20200110_085851_001](https://user-images.githubusercontent.com/59736115/72159167-c6f98980-3389-11ea-9b4b-351e36ac4015.jpg)
![20200110_085916](https://user-images.githubusercontent.com/59736115/72159197-d7116900-3389-11ea-8691-58f17ccfbede.jpg)

 - OS: Windows 10
 - Browser: Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by brandonbloch** [comment]
Hi @mygoodname631,

Sorry about the delay in response. Upon investigation, we found that the issue is caused by some defects in your STLs that are affecting the calculations for where the model contains surfaces, and which color should be applied to them. Here's a screenshot from Simplify3D before and after running the "Identify Self Intersecting Surfaces" repair tool:

![Screen Shot 2020-02-05 at 11 54 10 AM](https://user-images.githubusercontent.com/217964/73863552-45710c00-480e-11ea-92b0-b139a2c30065.png)

![Screen Shot 2020-02-05 at 11 54 25 AM](https://user-images.githubusercontent.com/217964/73863565-49049300-480e-11ea-8320-0995d2c892bf.png)

Repairing the models does indeed fix the issue:

![Screen Shot 2020-02-05 at 11 55 14 AM](https://user-images.githubusercontent.com/217964/73863636-6174ad80-480e-11ea-973c-b1d0ca555137.png)

CANVAS does not currently have any mesh analysis or repair tools built-in, which is why these issues are hard to detect until the project has been sliced—especially for this type of defect, which doesn't produce any noticeable issues when visualizing the model. Please do know that adding this type of functionality is on our radar! For now however, I would recommend re-exporting the models (if you created them) or repairing them yourself using a program like [Meshmixer](http://www.meshmixer.com). Let us know if you have any questions!

Cheers,
Brandon
