### ISSUE TITLE
Just to confirm - Single material splicing currently?

### ISSUE THREAD

**Issue by awr4sc** [MosaicManufacturing/canvas-issues#15]
I do not see any options to splice different materials (tpu, pla, etc) or settings like in Chroma; i'll assume this is a future development?

Also the slider bars on the bottom of the screen and right of the screen do not seem to do anything once you progress to the preview window. Something to preview layers at a later point?

![image](https://user-images.githubusercontent.com/33534561/44613845-4f987980-a7d7-11e8-9e64-ebe40dead7c5.png)

**Comment by awr4sc** [comment]
Just a bit of testing and a few more questions? or requests.  Print summary tells you the drive, and length, but not the colour; could you identify the colour for the drive in the summary. 
![image](https://user-images.githubusercontent.com/33534561/44624427-e9c9f180-a8ab-11e8-8c82-e9d0453b9a80.png)

Also there does not appear to be any way to label the colours, so, when loaded into palette+ the are listed as "default" on the palette+ instead of "blue", "red" etc. 
![image](https://user-images.githubusercontent.com/33534561/44624460-91dfba80-a8ac-11e8-9832-12070df20218.png)


Just a side note, the drives appeared backwards when I switched to chroma. So a job sliced in canvas had inputs that were equivalent to Drive 1 = 4, drive 3 = drive 2. Just an odd observation. Same print, same colours etc.

**Comment by brandonbloch** [comment]
Hi @awr4sc, you're correct on both counts.

Material profiles (along with splice settings) are still in development, but rest assured that they are high on our list of priorities. This will also include the ability to name the four inputs, which would show up on Palette.

The sliders are indeed for previewing the toolpaths created when slicing (the intent is that the Preview step visualizes these toolpaths instead of the solid models); this preview is currently in development as well.

Good idea re. showing the color for each drive! We will add that to our list.

As for the drives appearing backwards, which slicer were you using for the Chroma print? If the slicer lets you choose the actual tool for printing each model, then this would be suspicious, but if you simply tell it which models to print in the same color, it likely decides which tool to use for each group in its own way, which could depend on a number of factors based on how the logic is implemented. **TL;DR** it shouldn't be a problem, but that is interesting to note.

Cheers,
Brandon
