### ISSUE TITLE
Feature request: Add gcode from other slicer and prep the file for Palette

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [MosaicManufacturing/canvas-issues#152]
**Is your feature request related to a problem? Please describe.**
Right now, I use PrusaSlicer with P2PP before printing with the Canvase Hub. This feels like a hack, rather than a well implemented solution. It may keep a lot of potential buyers from using this machine.
**Describe the solution you'd like**
Import multicolor gcode from third party slicer and prep the file for consumption by Palette.

**Describe alternatives you've considered**
At this stage, Canvas' limitations prohibit serious users from using it as their go to slicer.

**Additional context**

**Comment by brandonbloch** [comment]
Hi @MimbaMonkeyHouse,

Thank you for your request! I'd like to clarify a few things:

First of all, P2PP is a third-party software developed and maintained by members of the Palette community, not by Mosaic. Any usability concerns for it should be directed towards its development team or its [GitHub repository](https://github.com/tomvandeneede/p2pp).

Mosaic does, however, provide a desktop application called [Chroma](http://mm3d.co/chroma) which does exactly what you're looking for. It takes multi-extruder G-code generated by Simplify3D, Cura, Slic3r/PrusaSlicer (without running P2PP), and KISSlicer, and converts it to a single-extruder G-code with transition commands and corresponding Palette instructions. You can find guides for setting all these different slicers up and more on our [support website](http://support.mosaicmfg.com).

Because Chroma exists, and CANVAS already generates G-code that it knows more about than anything it could import after-the-fact, this is unlikely to ever be implemented. I hope that explanation makes sense and that Chroma does the job for you. You're very welcome to open a new issue (or multiple) requesting improvement of the limitations you referred to.

Cheers,
Brandon
