### ISSUE TITLE
Chroma layer by layer visualization

### ISSUE THREAD

**Issue by matheussavi1** [MosaicManufacturing/canvas-issues#192]
Hi!

I'm having trouble in color transitioning in the middle of  keychain calibration.
In chroma I was no able to see were and how the transitioning color occurs.
So it would be nice the feature of scroll layers to see how they are planned instead only top and bottom layers.

Thank you!

**Comment by brandonbloch** [comment]
Hi @matheussavi1, the G-code visualizer in Chroma is much less accurate than the one in Canvas, and unfortunately this feature is not likely to be added due to the complexity of that visualizer. However, most slicers compatible with Chroma will let you open the processed G-code file created by Chroma and preview it, which will let you see the density of each layer.

I would recommend reaching out to support@mosaicmfg.com for help with calibration issues if you haven't already!

Cheers,
Brandon
