### ISSUE TITLE
Skirt Generates Around Tower Instead Of Object

### ISSUE THREAD

**Issue by jph290** [MosaicManufacturing/canvas-issues#199]
When I generate a multi-material/multi-color print, the first material of the object prints immediately instead of having the skirt/brim print first.  The skirt is then generated around the transition tower as a brim.  I had the separation of the skirt set to 6mm and it generated a brim around the transition tower.

**Comment by brandonbloch** [comment]
Hi @jph290, thanks for reaching out!

The transition tower's brim is independent of the rest of the print, and is used for adhesion as well as ensuring Palette's first splice is long enough that the device can produce it. As such, the result is always a brim (i.e. 0 offset, rather than a skirt), and while there's a setting for the tower's minimum brim count (in the Transition section) the slicer may add more than this minimum if necessary.

The main print's skirt/brim should always be the first thing printed, right after the start sequence. If you've got the setting enabled, something else could be causing it not to be generated (again, this would be independent of the transition tower). Would you be able to share your project here or to canvas@mosaicmfg.com so we can take a closer look at the issue?

Cheers,
Brandon

**Comment by jph290** [comment]
Here is a link to the project.  https://share.canvas3d.io/projects/356fbf8916feea4e4868c171c294eb20

**Comment by brandonbloch** [comment]
Thanks for responding so quickly!

It looks like your project doesn't have a skirt/brim enabled:

<img width="663" alt="Screen Shot 2021-01-04 at 12 39 46 PM" src="https://user-images.githubusercontent.com/217964/103563025-1170f180-4e8a-11eb-8b6e-3b5f054022d1.png">

After toggling the checkbox (and setting the horizontal gap to 6 mm) the skirt appears as expected:

<img width="455" alt="Screen Shot 2021-01-04 at 12 40 23 PM" src="https://user-images.githubusercontent.com/217964/103563067-26e61b80-4e8a-11eb-8491-0d13f426a7c1.png">

I'm closing this issue as resolved, but please feel free to comment/reopen if it still isn't working for you!

Cheers,
Brandon
