### ISSUE TITLE
Shared models with custom supports don't slice with supports

### ISSUE THREAD

**Issue by cscashby** [MosaicManufacturing/canvas-issues#260]
**Describe the bug**
When sharing a model with custom supports, the support settings do carry forward to the print but until going into 'edit custom supports' and saving, no supports are sliced.

**To Reproduce**
1. Go to one account and create a project, define custom supports
2. Share project with another account
3. Open project in second account and slice
4. Note no supports
5. Return to edit and edit custom supports, note custom surfaces are defined
6. Save supports
7. Slice again
8. Note supports in preview

**Expected behavior**
If I share a model I'd expect supports to be sliced if specified in the model

**Comment by brandonbloch** [comment]
Hi @cscashby, thanks for the report. This is actually intended; if not importing a style profile along with the project, we simply use the settings from the profile used for the imported project. The rationale being that if a different printer is being used, there may be different characteristics (e.g. different maximum overhang angles) that require the user to make a decision regarding these settings.

One thing to note is that there is in fact a bug related to "Import essential styles"; if the shared style profile does have custom supports enabled, the import process would only set the new project to use standard supports. It doesn't sound like this is the case you're running into, but this bug in particular has now been identified thanks to you and will be fixed shortly.

Since the behaviour described in this report is intended, I'm going to close the issue. If there's some aspect of this that we're missing, or another bug related to this issue, please feel free to reply here with additional info.

Thanks,
Brandon
