### ISSUE TITLE
Server Error 3007 when slicing.

### ISSUE THREAD

**Issue by DataDink** [MosaicManufacturing/canvas-issues#266]
**Describe the bug**
The following STL code will not slice:

```
solid
facet normal 0.000000 -1.000000 0.000000
outer loop
vertex 25.000000 -25.000000 0.000000
vertex -25.000000 -25.000000 10.000000
vertex -25.000000 -25.000000 0.000000
endloop
endfacet
facet normal 0.000000 0.000000 -1.000000
outer loop
vertex -25.000000 25.000000 0.000000
vertex 25.000000 -25.000000 0.000000
vertex -25.000000 -25.000000 0.000000
endloop
endfacet
facet normal -1.000000 0.000000 0.000000
outer loop
vertex -25.000000 -25.000000 10.000000
vertex -25.000000 25.000000 0.000000
vertex -25.000000 -25.000000 0.000000
endloop
endfacet
facet normal 0.000000 0.000000 1.000000
outer loop
vertex 25.000000 -25.000000 0.000000
vertex -25.000000 25.000000 0.000000
vertex -25.000000 -25.000000 10.000000
endloop
endfacet
endsolid
```

**To Reproduce**
1. Go to (https://canvas3d.io/projects)
2. Click on `+ New Project`
3. Save the above STL code to a file
4. Add the file to the project
5. Click `Slice`
6. Observe -> Slicing gets to around 4% or 5% and errors out with `Internal server error 3007`

**Expected behavior**
The slicing process on this shape to complete.

**Screenshots**

**Operating System (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 113.0.5672.126

**Additional context**
Sample project that won't slice: (https://share.canvas3d.io/projects/a1de96fc9e033eb8eec89d589a234cd2)

**Comment by brandonbloch** [comment]
Hi @DataDink,

Thanks for reporting this, and for providing the STL file! It turns out the issue was related to using Slic3r with STL files containing less than 6 triangles. This issue has been resolved and a fix is now deployed, so slicing this file should work as expected with both slicing engines now.

Closing this issue as resolved, but feel free to comment/re-open the issue if you're still experiencing any problems.

Thanks, and happy printing,
Brandon
