### ISSUE TITLE
GCode exported from Canvas to USB is not shown in the USB File Section at Palette3Pro 

### ISSUE THREAD

**Issue by HarlekinSimplex** [MosaicManufacturing/canvas-issues#279]
**Description:**
Today I tried to print some .gcode from Canvas with my Palette3Pro connected to a Snapmaker Artisan by transporting the file from canvas to the p3p using a USB stick, because sending the file to the p3p via the network directly resulted in a Error 500 from the Device. 
The gcode file exported from Canvas was succesfully stored on the stick and it was available in the Artisan USB menu as well. So the stick was fine and the file available as well.
However the stick was not accepted by p3p or the file was not found by p3p though it was on the stick. 
I tried this with different USB sticks, none worked though all of them worked with my PC, Laptop and the Artisan. 

**Steps to reproduce the behavior:**
1. Export a .gcode file with Canvas on a USB Stick 
2. Plug it into Palette3P
3. Try to open/print the File 
4. The file is not available in the Palette3Pro USB file list

**Expected behavior:**
The .gcode file exported to a USB stick shall be seen and able to be selected and printed by p3p. 

**Screenshots**

**Operating System:**
 - OS: MacOS, Win 10
 - Browser: Brave and Firefox
 - Palette3Pro: Most recent (May 24)

**Comment by brandonbloch** [comment]
Hi @HarlekinSimplex,

Palette 3 and Palette 3 Pro do not currently support printing single-color files (e.g. .gcode rather than .mcfx) which is why these files aren't showing up on the device.

I'll close this issue as it isn't related to Canvas, but I invite you to get in touch with our Customer Success team at support@mosaicmfg.com to request this as a feature or get more information for alternative approaches.

Cheers,
Brandon
