### ISSUE TITLE
No extruder or bed temperature variables in custom start scripts

### ISSUE THREAD

**Issue by HFMan** [MosaicManufacturing/canvas-issues#43]
Most slicers (actually all that I use, like Simplify3d, Cura, and Slic3r) allow variable substitution in custom start and end scripts.  I do not see this capability in Canvas.  For example, here is my standard start script I use in Simplify3D- this is highly customized and needed to have near perfect mesh leveling (it centers around pre-heating the pinda probe on a MK3).  The lines that are bold show where I need variable substitution- otherwise this start script will not work.

M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations
M203 X200 Y200 Z12 E120 ; sets maximum feedrates mm/sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (T)
M205 X10 Y10 Z0.4 E2.5 ; sets the jerk limits mm/sec
G28 W ; home all without mesh bed level
M104 S0 ; Turn off all heaters
G0 Z100 ; PINDA cooling position
**M140 S[bed0_temperature] T0 ; Get bed started helps with mesh leveling**
**M190 S[bed0_temperature] T0 ; wait for bed temp**
M140 S0 ; Turn off all heaters
M106 S255 ; turn on fan
G0 Z100 ; PINDA cooling position
M860 S35 ; wait until PINDA is <= 34C
M107 ; turn off fan
**M140 S[bed0_temperature] T0 ;**
**M190 S[bed0_temperature] T0 ; wait for bed temp**
M104 S170 T0 ; 
M109 S170 T0 ; Wait for nozzle to reach 40 degrees below first layer temp
G0 X50 Y50 Z0.15 ; this is a good PINDA heating position
M860 S35 ; wait until PINDA is >= 35C
G28 W ; home all axes without mesh bed leveling
G80 ; run mesh bed leveling routine
G1 X5 Y0 Z50 F1200 ; Move the nozzle up a bit as it is going to ooze ;
**M104 S[extruder0_temperature] T0 ; set first layer temp**
**M109 S[extruder0_temperature] T0 ; wait for extruder temp**
G1 X-5 Y0 Z-50 F1200 ; Lower the nozzle back ;
G1 Y-3.0 F1000.0 ; prepare to prime
G92 E0 ; reset extrusion distance
G1 X60.0 E8  F1000.0 ; priming
G1 X100.0 E11  F1000.0 ; priming
M900 K45 ; LA for PLA

These lines show as RED in the canvas edit dialog for the start sequence (understandable).

**Comment by brandonbloch** [comment]
Hi @HFMan,

CANVAS actually does have support for this! I have also personally been frustrated by the lack of documentation in other slicers around which variables they support.

If on the screen for editing your printer's start and end sequences, you can enter a larger editor view by clicking one of the "expand" buttons:

<img width="928" alt="screen shot 2018-11-21 at 9 15 54 am" src="https://user-images.githubusercontent.com/217964/48846967-69ae0d80-ed6e-11e8-9ea6-4bf9299b044d.png">

Clicking the (?) icon will display the full list of supported variables:

<img width="924" alt="screen shot 2018-11-21 at 9 17 25 am" src="https://user-images.githubusercontent.com/217964/48846985-7af71a00-ed6e-11e8-89ab-4288aff27a99.png">

In your case, you'll want to use the following variables:

| Replace | With |
|-|-|
| `[bed0_temperature]` | `<BED>` |
| `[extruder0_temperature]` | `<TEMP>` |

The start/end sequence editor will also auto-complete variables for you as you type them:

<img width="927" alt="screen shot 2018-11-21 at 9 21 40 am" src="https://user-images.githubusercontent.com/217964/48847170-e4772880-ed6e-11e8-8181-82e9b6f2abf9.png">

I hope that helps! I'm closing this issue since this feature exists. If you have any other questions or comments on the process feel free to comment further on this issue, or open a new one.

Cheers,
Brandon
