### ISSUE TITLE
canvas online slicing 

### ISSUE THREAD

**Issue by topautotech1981** [MosaicManufacturing/canvas-issues#74]
*internal server error displayed when attempting to slice any model in all browsers
![50380103-ef9dcc80-062a-11e9-9385-d791215f41e1](https://user-images.githubusercontent.com/46872884/51444191-87dab000-1cc2-11e9-9f40-1c4e2d8a2f32.PNG)
 same issue that was stated in canvas#62 by 
cmbrowning and SlyFox3007

**Comment by topautotech1981** [comment]
tried clicking slice many times and restarting browser and different models

**Comment by Madam21** [comment]
Same, wish Mosaic would comment on this issue. Sucks having a expensive paper weight....

**Comment by brandonbloch** [comment]
Hi everyone,

Our apologies about this. Some of our servers went down for about a 24 hour period over the weekend, resulting in some users being unable to slice entirely. We understand that there's nothing more frustrating than encountering a problem you can't work around in any way. Please know that this issue is a top priority for us, and we're working on resolving these issues entirely so that the slicing process does not experience this type of outage in the future (as well as being faster overall).

We have brought the servers back online, so you should now be able to slice once again. I'll leave this issue up for now so that others can follow along here. Please let us know if you have any questions or if you're still experiencing this issue.

Cheers,
Brandon

**Comment by r3df0xd13** [comment]
Having similar issue now. When slicing my model, Canvas will reach 1%-8% depending on the size of the model and then generate a Server Timed Out While Slicing error message. I have reached out via Email and Direct message without success
