### ISSUE TITLE
Actively support touch controls

### ISSUE THREAD

**Issue by bil-bas** [MosaicManufacturing/canvas-issues#85]
I can use most, but not all, of the webpage with my tablet.

The only thing that I can find which is impossible is to be able to drag colours from the dots onto models (some other bits are fiddly, but nothing else is actually impossible)

P2 and printer are in a different room than my desktop PC and it would be great to be able to use my tablet to control canvas when in my workshop (or without having to boot up my PC).

**Comment by brandonbloch** [comment]
🎉

**Comment by bil-bas** [comment]
Thanks - so quick! However, now it is very difficult to open/close the
materials window, and if it fails, you also end up changing the colour of what you last painted.

**Comment by bil-bas** [comment]
Oops, yes, if you touch the white border around the paint colour, the material window toggles. Touch the colour and you set that colour.

**Comment by brandonbloch** [comment]
Hmm, sounds like I spoke a bit soon. This was working during testing but some further optimizations were required and it seems they have broken this aspect of the interaction. I've dug into why and it turns out that trying to fix it has unfortunately made things worse, so we're going to leave this behaviour as-is for now.

Please note that proper mobile/touch support is on our roadmap and we will be properly re-working this interaction (along with optimizations of the general layout for small screens) at that time. In the meantime, I hope this level of support will suffice!

Cheers,
Brandon

**Comment by bil-bas** [comment]
It works now, even if it is a bit fiddly to use. I am happy :)
